version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - echo "Hello World"
      - npm run build
      - ls

artifacts:
  files:
    - 'build/**/*'
    - 'package.json'
    - 'package-lock.json'
    - 'Procfile'
    - 'node_modules/**/*'